### ISSUE TITLE
Can withSubscription also take the current state of the model like Elm does?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [andrejewski/raj-subscription#3]
In Elm, subscriptions take in the model along with the dispatch function, so this example:
```js
function tickSubscription () {
  let timerId
  let count = 1
  return {
    effect (dispatch) {
      timerId = setInterval(() => dispatch(count++), 1000)
    },
    cancel () {
      clearInterval(timerId)
    }
  }
}
```
could be 
```js
function tickSubscription () {
  let timerId
  let count = 1
  return {
    effect (dispatch, currentState) {
      timerId = setInterval(() => { 
            if (currentState.countSoFar < 10) {
                   count = count + 1;
                   dispatch(count);
            } else {  
                this.cancel(); 
                // or this.cancel.bind(this)? not sure how js works :p 
            }
      }, 1000)
    },
    cancel () {
      clearInterval(timerId)
    }
  }
}
```
Would this be possible to implement with the current design of the runtime?

**Comment by andrejewski** [comment]
Using `withSubscriptions`, the `subscriptions` method receives the current state and you can pass whatever is in the model as arguments to subscription creators like `tickSubscription`. So you could do:

```js
function tickSubscription (shouldContinue) {
  let timerId
  return {
    effect (dispatch, currentState) {
      timerId = setInterval(() => { 
            if (shouldContinue) {
                   dispatch();
            }
      }, 1000)
    },
    cancel () {
      clearInterval(timerId)
    }
  }
}
```

However, if `shouldContinue` is false we should cancel the subscription which `withSubscription` will do for us if we write our `subscriptions` function as:

```js
const subscriptions = model => ({
  tick: model.shouldTick && tickSubscription
})
```

In general, a subscription should never need the whole program model and should always take the minimum about of information. In this case, `tickSubscription` doesn't need to be aware of anything. However, a good parameter for tickSubscription would be the interval duration, like so:

```js
const subscriptions = model => ({
  tick: model.shouldTick && () => tickSubscription(model.intervalDuration)
})
```

And then tickSubscription looks like:

```js
function tickSubscription (intervalDuration) {
  let timerId
  return {
    effect (dispatch, currentState) {
      timerId = setInterval(() => { dispatch(); }, intervalDuration)
    },
    cancel () {
      clearInterval(timerId)
    }
  }
}
```

**Comment by Zaid-Ajaj** [comment]
@andrejewski Thanks a lot for the clear explaination! I will try play around with this :smile:

**Comment by andrejewski** [comment]
@Zaid-Ajaj no problem
